//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APITest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsersPerfilesAsignado
    {
        public Nullable<int> CodigoAspNetUsersPefilesAsignados { get; set; }
        public int CodigoPerfil { get; set; }
        public int CodigoEmpresa { get; set; }
        public int CodigoMetodo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual PerfilesMetodo PerfilesMetodo { get; set; }
    }
}
