//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APITest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metodo
    {
        public Metodo()
        {
            this.PerfilesMetodos = new HashSet<PerfilesMetodo>();
        }
    
        public int CodigoMetodo { get; set; }
        public string Metodo1 { get; set; }
        public string Controller { get; set; }
        public Nullable<bool> Informatica { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual ICollection<PerfilesMetodo> PerfilesMetodos { get; set; }
    }
}
