//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APITest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulo
    {
        public Modulo()
        {
            this.Modulos1 = new HashSet<Modulo>();
        }
    
        public int CodigoModulo { get; set; }
        public Nullable<int> CodigoModuloPadre { get; set; }
        public string Titulo { get; set; }
        public string Url { get; set; }
        public string ClaseIcono { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual ICollection<Modulo> Modulos1 { get; set; }
        public virtual Modulo Modulo1 { get; set; }
    }
}
