//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APITest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilesMetodo
    {
        public PerfilesMetodo()
        {
            this.AspNetUsersPerfilesAsignados = new HashSet<AspNetUsersPerfilesAsignado>();
        }
    
        public int CodigoPerfilesMetodos { get; set; }
        public int CodigoPerfil { get; set; }
        public int CodigoEmpresa { get; set; }
        public int CodigoMetodo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual ICollection<AspNetUsersPerfilesAsignado> AspNetUsersPerfilesAsignados { get; set; }
        public virtual Metodo Metodo { get; set; }
        public virtual Perfile Perfile { get; set; }
    }
}
