//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APITest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        public int CodigoSucursal { get; set; }
        public int CodigoEmpresa { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Area { get; set; }
        public string Telefono { get; set; }
        public bool Estado { get; set; }
    }
}
